name: Deploy to AWS S3
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build frontend
        run: npm run build
      
      - name: Debug directories
        run: |
          ls -la ${{ github.workspace }}
          ls -la ${{ github.workspace }}/build || echo "Build directory not found"
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/sd11-final-sprint-fe
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Check AWS identity
        run: aws sts get-caller-identity
      
      - name: Upload to S3
        run: |
          aws s3 sync ${{ github.workspace }}/build s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
